GO
ALTER DATABASE [AplicationComercial] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AplicationComercial] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AplicationComercial] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AplicationComercial] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AplicationComercial] SET ARITHABORT OFF 
GO
ALTER DATABASE [AplicationComercial] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AplicationComercial] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AplicationComercial] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AplicationComercial] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AplicationComercial] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AplicationComercial] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AplicationComercial] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AplicationComercial] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AplicationComercial] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AplicationComercial] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AplicationComercial] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AplicationComercial] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AplicationComercial] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AplicationComercial] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AplicationComercial] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AplicationComercial] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AplicationComercial] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AplicationComercial] SET RECOVERY FULL 
GO
ALTER DATABASE [AplicationComercial] SET  MULTI_USER 
GO
ALTER DATABASE [AplicationComercial] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AplicationComercial] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AplicationComercial] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AplicationComercial] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'AplicationComercial', N'ON'
GO